#!/usr/bin/env bash
#shellcheck disable=SC2086


subdomain=$2
domain=$1

function www {
	record_type=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
	destination=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $5}')
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ $# -le 2 ]; then
	www
fi
