#!/usr/bin/env bash
# a script that installs and sets up nginx

# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Create a simple HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html
