#!/usr/bin/env bash
# Configures Nginx for 301 redirect

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx
echo "Hello World!" > sudo /var/www/html/index.html
# Configure redirect
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
# Restart Nginx
service nginx restart
