#!/usr/bin/env bash
# a script that configures a custom 404 page

apt-get update

apt-get install nginx -y

echo "Ceci n'est pas une page" > sudo /var/www/html/404.html

sed -i '/server_name _;/a\\tlocation /redirect_me { return 301 https://www.google.com; }' /etc/nginx/sites-available/default

sed -i '/server_name _;/a\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx start
