#!/usr/bin/env bash


apt-get update

apt-get install nginx -y

echo "Ceci n'est pas une page" > sudo /var/www/html/404.html

sed -i '/server_name _;/a \    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# sed -i '/server_name _;/a \     error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx start
