#!/usr/bin/env bash
# a script that configures a custom http response header on a brand new Ubuntu machine

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a\\tlocation /redirect_me { return 301 https://www.duckduckgo.com; }' /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
