#!/usr/bin/env bash
# a script that configures a custom http response header on a brand new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
# echo "Hello World!" > /var/www/html/index.html
sudo sed -i "47a\\\t#add custom response header:\n\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
