#!/usr/bin/env bash
#installing haproxy
sudo apt update
sudo apt install haproxy -y
sudo tee -a /etc/haproxy/haproxy.cfg << EOF

listen myserver
    bind *:80
    balance roundrobin
    server server1 100.25.220.64:80 check
    server server2 100.26.233.66:80 check
EOF
sudo service haproxy restart
