#!/usr/bin/env bash
#installing haproxy
sudo apt update
sudo apt install haproxy -y
sudo tee -a /etc/haproxy/haproxy.cfg << EOF

listen myserver
    bind *:80
    balance roundrobin
    server 382579-web-01 54.85.45.15:80 check
    server 382579-web-02 35.175.65.117:80 check
EOF
sudo service haproxy restart
