#!/usr/bin/env bash


# Copy the hosts file to a new file
cp /etc/hosts /etc/hosts.new

# Update the hosts.new file to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts.new
echo -e '\n# Facebook\n8.8.8.8 facebook.com' >> /etc/hosts.new

# Copy the modified hosts.new file back to /etc/hosts
cp -f /etc/hosts.new /etc/hosts
