#!/usr/bin/env bash
# A scrpt that runs nginx as nginx

# Stop the nginx service
sudo service nginx stop

# Add the nginx user to the nginx configuration
echo "user nginx;" >> /etc/nginx/nginx.conf

# Set the correct permissions for the nginx configuration file
chmod 644 /etc/nginx/nginx.conf

# Update the listening port to 8080 in the default site configuration
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Start the nginx service as the nginx user
sudo -u nginx service nginx start

